### ISSUE TITLE
Identify region of interest in a picture

### ISSUE THREAD

**Issue by Scarabyte** [Scarabyte/SSW690-Project#18]
From an image of a road, identify the area and features of interest (i.e. locate the lane markings)

**Comment by Scarabyte** [comment]
I think the objective of this defect is to crop the image so we don't get 'distracted' by unimportant features like trees on the side of the road or clouds in the sky. However, will this be handled by the image filtering routines? Do we need a separate issue? (From the filtered image, we still have to focus on the parts that we're interested in.)

**Comment by bsapana** [comment]
Yes, this will be covered in image filtering and edge detection stories.

**Comment by kroseberry13SIT** [comment]
This may require calibration to determine the extent of the image to crop. Initially, we can make an assumption based on empirical evidence. But a full product, due to the different geometries in camera lenses, will need to be user-adjustable.

Another aspect to consider is whether the cropped area needs to be adjusted to "look into" the direction the vehicle is turning while driving around a bend in a road.

**Comment by Scarabyte** [comment]
Seems like this is part of converting the image to 'sky view' #46

**Comment by Scarabyte** [comment]
There are two ways of doing this: either a fixed portion of the image, or dynamically determined from the road horizon.
To start, we should use the fixed portion which would be simpler to implement, and then consider using the dynamic approach later on.

**Comment by rakshithv** [comment]
Initial research shows the following options:
1) Take only the bottom part of the image as the area of interest, or try and find horizontal horizon line and crop everything above that
2) Create a polygon of some sort (encompassing line starts at the bottom of the image and ending at a single point beyond the horizon
3) Instead of cropping the image to areas of interest, filter the image for only colors that matter (in this case, yellow and white)

**Comment by rakshithv** [comment]
I have been trying to use this as a context to implement this story
https://medium.com/@gruby/opencv-for-lane-detection-carnd-f9d58d077ee2

The steps seem to be:
1) Create a mask with an empty image
2) Create the polygon (area of interest)
3) And the mask with the image
This will create only the lane highlighted, and all other objects in the image are removed.

**Comment by rakshithv** [comment]
Closing this because area of interest has been incorporated by commit 7ad1bb3 as part of sky/view
