### ISSUE TITLE
Start the application

### ISSUE THREAD

**Issue by kroseberry13SIT** [Scarabyte/SSW690-Project#24]
As a user, I want to start the application by pressing the application icon

Developer Note: Simple application startup user story.

**Comment by bsapana** [comment]
Once we start the application, do we need to choose Android device to run it on? That was happening for colorblob sample app.

**Comment by Scarabyte** [comment]
I think that only happens when you run it from Android Studio. Once it's installed on your phone, you should just press the app icon. Did you see something else when you were running it?

**Comment by Scarabyte** [comment]
Update the Android Studio project to identify this as "Back Seat Drivers" instead of "OpenCV Project".

**Comment by bsapana** [comment]
To identify "OpenCV Project" as "Back Seat Drivers" on Android Device and Studio, following steps were performed.

1. Open existing Android opencv_proj in studio
2. In the drop down click Android option to see all subfoleders
3. Right click on Java -> com.example.opencvproject package folder 
4 Select Refactor -> Rename
5 Warning pop up with list of subdirectories like below..

Multiple directories correspond to package
com.example.opencvproject:

C:\Sapana\SSW690-Project\src\opencv_proj\app\src\main\java\com\example\opencvproject
C:\Sapana\SSW690-Project\src\opencv_proj\app\src\androidTest\java\com\example\opencvproject
C:\Sapana\SSW690-Project\src\opencv_proj\app\src\test\java\com\example\opencvproject

also generated:
C:\Sapana\SSW690-Project\src\opencv_proj\app\build\generated\source\r\debug\com\example\opencvproject
C:\Sapana\SSW690-Project\src\opencv_proj\app\build\generated\source\buildConfig\debug\com\example\opencvproject

Do you want to rename the whole package or directory 
C:\Sapana\SSW690-Project\src\opencv_proj\app\src\main\java\com\example\opencvproject only? 

6. Click Rename Pacakge (not rename subdirectories)
7. Studio willl detect all the files which require update fo rthe name change
8. Click Do Refactor
9. You will see actual refactor -> renamed happened in the project 
10. To update all the related files with new app name, Select File -> Sync Project with Gradle files optin on top menu
11. Also, update app -> res -> values -> strings.xml 
change <string name="app_name">BackSeatDrivers</string>
12. Select Build -> Clean Project
13. Select Build -> Rebuild Project
14. Run the application with your device, now you will see app icon with name "BackSearDrivers' on your device

I have purposely kept main project name as it is (opencv_proj) otherwise it would consider as a different project in github. Renaming packages, references, app name and gradle files satisfy our purpose.

**Comment by Scarabyte** [comment]
Remember to also enable the Camera permission on the phone.

**Comment by bsapana** [comment]
Code changed merged in master. Device displays correct app name 'BackSeatDrivers'.
